apiVersion: v1
kind: Service
metadata:
 name: application-lb-service
spec:
 type: LoadBalancer
 ports:
 - targetPort: 80
   port: 80
   nodePort: 30081
 selector:
  app: myapp # any custom name
  version: blue