name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          minikube start --driver=none
          kubectl config use-context minikube

      - name: Load Docker images
        run: |
          minikube image load docker.io/library/blue_env:latest
          minikube image load docker.io/library/green_env:latest

      - name: Apply Blue Deployment
        run: |
          kubectl apply -f kubernets_yamls/blue_version.yaml
          kubectl apply -f kubernets_yamls/service.yaml

      - name: Apply Green Deployment
        run: |
          kubectl apply -f kubernets_yamls/green_version.yaml

      - name: Verify Green Deployment
        id: verify_green
        run: |
          kubectl rollout status deployment/myapp-deployment-green
        continue-on-error: true

      - name: Set Deployment Verification Status
        id: set_status
        shell: powershell
        run: |
          if ($LASTEXITCODE -eq 0) {
            Write-Output "Green deployment successful."
            Add-Content -Path $env:GITHUB_ENV -Value "RESULT=stable"
          } else {
            Write-Output "Green deployment failed. Continuing with blue deployment."
            Add-Content -Path $env:GITHUB_ENV -Value "RESULT=unstable"
          }
          echo "code is ${{LASTEXITCODE}}"

      - name: Debug RESULT Variable
        run: |
          echo "RESULT is ${{ env.RESULT }}"

      - name: Switch Traffic to Green and delete old deployment
        if: ${{ env.RESULT == 'stable' }}
        run: |
          kubectl patch service application-lb-service --type=merge -p '{\"spec\": {\"selector\": {\"app\": \"myapp\", \"version\": \"green\"}}}'
          kubectl delete deployment myapp-deployment-blue

      - name: Switch Traffic to Blue
        if: ${{ env.RESULT == 'unstable' }}
        run: |
          kubectl patch service application-lb-service --type=merge -p '{\"spec\": {\"selector\": {\"app\": \"myapp\", \"version\": \"blue\"}}}'

      - name: Run the Application for 15 Seconds
        shell: powershell  # Specify PowerShell as the shell
        run: |
          powershell -Command "Start-Sleep -Seconds 15; minikube service application-lb-service"
          Stop-Process -Name "minikube" -Force
        continue-on-error: true
          
          
      - name: Stop the Application
        shell: powershell  # Specify PowerShell as the shell
        run: |
          Stop-Process -Name "minikube" -Force
