name: Debugging Workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print system info
        run: |
          echo "System Information"
          uname -a
          lsb_release -a

      - name: Debug Docker
        run: |
          docker --version
          docker info

      - name: Debug Minikube
        run: |
          minikube version
          minikube status

      - name: Print environment variables
        run: |
          printenv
