name: Runner Health Check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Check Runner Status
        run: |
          echo "Checking system info"
          uname -a
          df -h
          free -m
          echo "Docker version"
          docker --version
          docker info
