name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          minikube start --driver=none
          kubectl config use-context minikube

      - name: Load Docker images
        run: |
          minikube image load docker.io/library/blue_env:latest
          minikube image load docker.io/library/green_env:latest

      - name: Apply Blue Deployment
        run: |
          kubectl apply -f kubernets_yamls/blue_version.yaml
          kubectl apply -f kubernets_yamls/service.yaml

      - name: Apply Green Deployment
        run: |
          kubectl apply -f kubernets_yamls/green_version.yaml

      - name: Verify Green Deployment
        id: verify-green
        run: |
          kubectl rollout status deployment/myapp-deployment-green --timeout=60s

      - name: Switch Traffic to Green (If Deployment Succeeds)
        if: success()  # Only run if the previous step succeeded
        run: |
          kubectl patch service application-lb-service --type=merge -p '{\"spec\": {\"selector\": {\"app\": \"myapp\", \"version\": \"green\"}}}'

      - name: Cleanup Old Deployment
        if: success()  # Only run if the green deployment succeeds
        run: |
          kubectl delete deployment myapp-deployment-blue

      - name: Rollback to Blue (If Green Deployment Fails)
        if: failure()  # Only run if the green deployment fails
        run: |
          kubectl rollout undo deployment/myapp-deployment-blue
          kubectl patch service application-lb-service --type=merge -p '{\"spec\": {\"selector\": {\"app\": \"myapp\", \"version\": \"blue\"}}}'

      - name: Run the application
        run: |
          minikube service application-lb-service
